import type { Metadata } from "next";
import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import Background from "@/components/Background";
import NavigationLinks from "@/components/NavigationLinks";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <div className="h-screen">
      <div className="h-[8%]">
        <NavBar />
      </div>
      <div className="drawer xl:drawer-open h-[92%]">
        <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content border-y-[1px] border-base-300 flex flex-col h-full overflow-hidden">
          <Background />
          <div className="h-full p-[3%] overflow-y-scroll">
            {children}
          </div>
        </div>
        <div className="drawer-side z-50 xl:h-full">
          <label htmlFor="my-drawer-3" aria-label="close sidebar" className="drawer-overlay"></label>
          <ul className="menu bg-base-100 border-[1px] border-base-300 min-h-full w-80 p-4">
            <NavigationLinks />
          </ul>
        </div>
      </div>
    </div>
  );
}
